"""Screw-jack mechanism equations — Eq. 1, 4, 5, 6.

All units: inches [in], pounds-force [lbf], pounds per square inch [psi].
Source: SPE-232499-MS pp. 5, 11–12; Beer et al. (2015) Mechanics of Materials.
"""


def l_ot(delta_mu: float, delta_ot: float, l_fl: float) -> float:
    """Eq. 1 — Total axial displacement from screw-jack mechanism (in).

    L_OT = (ΔMU + ΔOT) × LFL

    SPE-232499-MS p. 5: 'The corresponding axial displacement (LOT) can be
    expressed as [Eq. 1] where LFL is thread lead.'

    Args:
        delta_mu: Make-up delta turns past shoulder point [rev].
            Experimentally determined from torque-turn plot (Fig. 11a).
        delta_ot: Operational delta turns applied by top drive [rev].
            Experimentally determined from torque-turn plot (Fig. 11b).
        l_fl: Thread lead — axial advance per full revolution [in/rev].
            BTC 5.5-in (5 TPI, API 5B): LFL = 0.200 in/rev (estimated).

    Returns:
        LOT total axial displacement [in].
    """
    if delta_mu < 0:
        raise ValueError(f"delta_mu must be ≥ 0, got {delta_mu}")
    if delta_ot < 0:
        raise ValueError(f"delta_ot must be ≥ 0, got {delta_ot}")
    if l_fl <= 0:
        raise ValueError(f"Thread lead l_fl must be positive, got {l_fl}")
    return (delta_mu + delta_ot) * l_fl


def epsilon_r(a_bccs: float, fa_pin_area: float, lf_area: float) -> float:
    """Eq. 4 — Relative strain fraction (dimensionless).

    εR = A_BCCS / (A_BCCS + FA_pin + LF_area)

    SPE-232499-MS p. 12 (confirmed against PDF images).
    'Assuming the strain is uniformly distributed within the elastic region
    of the material, the relative strain fraction εR... [is] defined as [Eq. 4].'

    εR represents the fraction of total interfacial area (BCCS + pin face +
    load flanks) attributable to the BCCS. By construction: 0 < εR < 1.

    Args:
        a_bccs: BCCS cross-sectional area [in²] — from Eq. 2.
        fa_pin_area: Pin face contact area [in²] — from Eq. 3.
        lf_area: Helical load-flank area [in²] — active thread contact.

    Returns:
        εR relative strain fraction [dimensionless, strictly in (0, 1)].
    """
    if a_bccs <= 0:
        raise ValueError(f"a_bccs must be positive, got {a_bccs}")
    if fa_pin_area <= 0:
        raise ValueError(f"fa_pin_area must be positive, got {fa_pin_area}")
    if lf_area <= 0:
        raise ValueError(f"lf_area must be positive, got {lf_area}")
    result = a_bccs / (a_bccs + fa_pin_area + lf_area)
    assert 0.0 < result < 1.0, (
        f"εR = {result:.6f} outside valid range (0, 1). "
        f"Inputs: A_BCCS={a_bccs}, FA_pin={fa_pin_area}, LF_area={lf_area}"
    )
    return result


def delta_displacement(lot: float, eps_r: float) -> float:
    """Eq. 5 — Effective elastic displacement of the BCCS (in).

    δ = LOT × εR

    SPE-232499-MS p. 12 (confirmed against PDF images).
    Since 0 < εR < 1, δ < LOT always — the BCCS absorbs only its proportional
    share of the total screw-jack advance.

    Args:
        lot: Total axial displacement from screw-jack — from Eq. 1 [in].
        eps_r: Relative strain fraction — from Eq. 4 [dimensionless, (0, 1)].

    Returns:
        δ effective elastic displacement of BCCS [in].
    """
    if lot < 0:
        raise ValueError(f"lot must be ≥ 0, got {lot}")
    if not (0.0 < eps_r < 1.0):
        raise ValueError(f"eps_r must be in (0, 1), got {eps_r}")
    result = lot * eps_r
    if lot > 0:
        assert result < lot, (
            f"δ ({result:.6f} in) must be less than LOT ({lot:.6f} in)"
        )
    return result


def f_tq(delta: float, E: float, a_bccs: float, l_b: float) -> float:
    """Eq. 6 — Axial screw-jack preload on the BCCS (lbf).

    F_TQ = δ × E × A_BCCS / L_B

    SPE-232499-MS p. 12 (confirmed against PDF images):
    'The total load on the BCCS generated by the screw-jack mechanism, FTQ,
    is calculated as [Eq. 6] where E is the Young's modulus of steel and LB
    is the coupling length. (Beer, 2015)'

    Hooke's law for an elastic bar: F = E × (δ/L) × A.

    Args:
        delta: Effective elastic displacement from Eq. 5 [in].
        E: Young's modulus of steel [psi]. P110: 30 × 10⁶ psi.
        a_bccs: BCCS cross-sectional area from Eq. 2 [in²].
        l_b: Coupling length [in].

    Returns:
        F_TQ screw-jack axial preload [lbf].
    """
    if delta < 0:
        raise ValueError(f"delta must be ≥ 0, got {delta}")
    if E <= 0:
        raise ValueError(f"Young's modulus E must be positive, got {E}")
    if a_bccs <= 0:
        raise ValueError(f"a_bccs must be positive, got {a_bccs}")
    if l_b <= 0:
        raise ValueError(f"Coupling length l_b must be positive, got {l_b}")
    return delta * E * a_bccs / l_b
